version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://RW_voyager:BR1wsbdVkZEZmHrz@voyager.gywtrkq.mongodb.net/?retryWrites=true&w=majority&appName=voyager
      - DATABASE_NAME=blockchainDatabase

