version: "3"

services:
  redis:
    image: "redis:alpine"

  web:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.celeryworker
    env_file:
      - .env
    depends_on:
      - redis

  beat:
    build:
      context: .
      dockerfile: Dockerfile.celerybeat
    env_file:
      - .env
    depends_on:
      - redis
